# This workflow will perform a build of the plugin and run any tests

name: Check IntelliJ-Automation-Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    uses: centic9/actions/.github/workflows/gradle-build.yml@1
